sla = input ('Digite algo: ')
print('O tipo primitivo desse valor é ', (type(sla)))
print('O que você digitou só tem letras?', sla.isalpha() )
print('O que você digitou só tem números?', sla.isnumeric())
print('O que você digitou é alfanumérico?', sla.isalnum())
print('O que você digitou está apenas em letras minúsculas?', sla.islower())
print('O que você digitou está apenas em letras maiusculas?', sla.isupper())
print('O que você digitou tem apenas espaço?', sla.isspace())
print('O que você digitou é capitalizado?', sla.istitle())
print('Ela é o amor da sua vida??')
print('SIMMMMMMMMMMMMMMMMMMMMMMM')